/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Logica;

import java.awt.Image;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseListener;

import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

import com.formdev.flatlaf.*;

import Recursos.ClassRecursos;
import java.awt.Color;

/**
 *
 * @author the_b
 */
public class NewJFrame extends javax.swing.JFrame implements ActionListener, KeyListener, MouseListener {

    private static final long serialVersionUID = 1L;

    Conversor conversor = new Conversor();
    ConversorTemperatura temp = new ConversorTemperatura();
    ClassRecursos recursos = new ClassRecursos();
    String m = "Moneda";

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();

        String imagePath = "/Recursos/aluraLatam.png";

        Image icon = new ImageIcon(getClass().getResource(imagePath)).getImage();
        this.setIconImage(icon);

        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoDeBotones = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        aluraLogo = new javax.swing.JLabel();
        BtnMoneda = new javax.swing.JToggleButton();
        BtnDistancia = new javax.swing.JToggleButton();
        BtnMasa = new javax.swing.JToggleButton();
        BtnVolumen = new javax.swing.JToggleButton();
        BtnTemperatura = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        Box1 = new javax.swing.JComboBox<>(MagUtil.Moneda);
        BtnConversor = new javax.swing.JButton();
        Box2 = new javax.swing.JComboBox<>(MagUtil.Moneda);
        jSpinner1 = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Txt1 = new javax.swing.JTextField();
        Txt2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JbackG2 = new javax.swing.JLabel();
        ConversionActual = new javax.swing.JLabel();
        Swith = new javax.swing.JToggleButton();
        JbackG = new javax.swing.JLabel();
        JbackG1 = new javax.swing.JLabel();


        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/blueSky.gif"))); // NOI18N
        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor");
        setBackground(new java.awt.Color(17, 58, 110));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(17, 58, 110));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aluraLogo.setBackground(new java.awt.Color(17, 58, 110));
        aluraLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/aluraLatam.png"))); // NOI18N
        jPanel2.add(aluraLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 21, -1, -1));

        GrupoDeBotones.add(BtnMoneda);
        BtnMoneda.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnMoneda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Moneda.png"))); // NOI18N
        BtnMoneda.setSelected(true);
        BtnMoneda.setText("Moneda");
        BtnMoneda.setFocusCycleRoot(true);
        BtnMoneda.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnMoneda.setMargin(new java.awt.Insets(2, -5, 3, 14));
        BtnMoneda.addMouseListener(this);
        BtnMoneda.addActionListener(this);
        jPanel2.add(BtnMoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 99, 150, 40));

        GrupoDeBotones.add(BtnDistancia);
        BtnDistancia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnDistancia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Distancia.png"))); // NOI18N
        BtnDistancia.setText("Distancia");
        BtnDistancia.setFocusCycleRoot(true);
        BtnDistancia.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnDistancia.setIconTextGap(0);
        BtnDistancia.setMargin(new java.awt.Insets(2, -5, 3, 14));
        BtnDistancia.addMouseListener(this);
        BtnDistancia.addActionListener(this);
        jPanel2.add(BtnDistancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 149, 150, 40));

        GrupoDeBotones.add(BtnMasa);
        BtnMasa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnMasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Masa.png"))); // NOI18N
        BtnMasa.setText("Masa");
        BtnMasa.setFocusCycleRoot(true);
        BtnMasa.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnMasa.setMargin(new java.awt.Insets(2, -25, 3, 14));
        BtnMasa.addMouseListener(this);
        BtnMasa.addActionListener(this);
        jPanel2.add(BtnMasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 199, 150, 40));

        GrupoDeBotones.add(BtnVolumen);
        BtnVolumen.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnVolumen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Volumen.png"))); // NOI18N
        BtnVolumen.setText("Volumen");
        BtnVolumen.setFocusCycleRoot(true);
        BtnVolumen.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnVolumen.setIconTextGap(0);
        BtnVolumen.setMargin(new java.awt.Insets(2, -8, 3, 14));
        BtnVolumen.addMouseListener(this);
        BtnVolumen.addActionListener(this);
        jPanel2.add(BtnVolumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 249, 150, 40));

        GrupoDeBotones.add(BtnTemperatura);
        BtnTemperatura.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnTemperatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/temperatura.png"))); // NOI18N
        BtnTemperatura.setText("Temperatura");
        BtnTemperatura.setFocusCycleRoot(true);
        BtnTemperatura.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnTemperatura.setIconTextGap(0);
        BtnTemperatura.setMargin(new java.awt.Insets(2, 5, 3, 14));
        BtnTemperatura.addMouseListener(this);
        BtnTemperatura.addActionListener(this);
        jPanel2.add(BtnTemperatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 299, 150, 40));

        jPanel1.setFocusCycleRoot(true);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Box1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(Box1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 120, 40));

        BtnConversor.setBackground(new java.awt.Color(19, 62, 115));
        BtnConversor.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BtnConversor.setForeground(new java.awt.Color(255, 255, 255));
        BtnConversor.setText("Convertir");
        BtnConversor.setMaximumSize(new java.awt.Dimension(100, 33));
        BtnConversor.setMinimumSize(new java.awt.Dimension(100, 33));
        BtnConversor.setName(""); // NOI18N
        BtnConversor.addMouseListener(this);
        BtnConversor.addActionListener(this);
        BtnConversor.addKeyListener(this);
        jPanel1.add(BtnConversor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 130, 40));

        Box2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Box2.addActionListener(this);
        jPanel1.add(Box2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 110, 40));

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(2, 0, 10, 1));
        jPanel1.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 50, 50));

        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setText("Limpiar");
        jButton1.addActionListener(this);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 110, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/OnE.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 170, 80));

        Txt1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Txt1.addKeyListener(this);
        jPanel1.add(Txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 120, 50));

        Txt2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Txt2.setToolTipText("Resultado");
        Txt2.setDisabledTextColor(new java.awt.Color(38, 38, 38));
        Txt2.setSelectionColor(new java.awt.Color(0, 142, 237));
        jPanel1.add(Txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 110, 50));

        jLabel4.setBackground(new java.awt.Color(187, 187, 187));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/arrowflat_blue.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 40, 40));
        jPanel1.add(JbackG2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 440, 110));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 430, 238));

        ConversionActual.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        ConversionActual.setForeground(new java.awt.Color(255, 255, 255));
        ConversionActual.setText(m);
        ConversionActual.setToolTipText(m);
        ConversionActual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ConversionActual.setIconTextGap(-50);
        jPanel2.add(ConversionActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 21, 293, 47));

        Swith.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/light (Custom1).png"))); // NOI18N
        Swith.setBorder(null);
        Swith.setBorderPainted(false);
        Swith.setContentAreaFilled(false);
        Swith.setOpaque(true);
        Swith.addActionListener(this);
        jPanel2.add(Swith, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 70, 47));
        jPanel2.add(JbackG, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 430, 350));
        jPanel2.add(JbackG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 350));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 350));

        pack();
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (evt.getSource() == BtnMoneda) {
            NewJFrame.this.BtnMonedaActionPerformed(evt);
        }
        else if (evt.getSource() == BtnDistancia) {
            NewJFrame.this.BtnDistanciaActionPerformed(evt);
        }
        else if (evt.getSource() == BtnMasa) {
            NewJFrame.this.BtnMasaActionPerformed(evt);
        }
        else if (evt.getSource() == BtnVolumen) {
            NewJFrame.this.BtnVolumenActionPerformed(evt);
        }
        else if (evt.getSource() == BtnTemperatura) {
            NewJFrame.this.BtnTemperaturaActionPerformed(evt);
        }
        else if (evt.getSource() == BtnConversor) {
            NewJFrame.this.BtnConversorActionPerformed(evt);
        }
        else if (evt.getSource() == Box2) {
            NewJFrame.this.Box2ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton1) {
            NewJFrame.this.jButton1ActionPerformed(evt);
        }
        else if (evt.getSource() == Swith) {
            NewJFrame.this.SwithActionPerformed(evt);
        }
    }

    public void keyPressed(java.awt.event.KeyEvent evt) {
        if (evt.getSource() == BtnConversor) {
            NewJFrame.this.BtnConversorKeyPressed(evt);
        }
        else if (evt.getSource() == Txt1) {
            NewJFrame.this.Txt1KeyPressed(evt);
        }
    }

    public void keyReleased(java.awt.event.KeyEvent evt) {
    }

    public void keyTyped(java.awt.event.KeyEvent evt) {
    }

    public void mouseClicked(java.awt.event.MouseEvent evt) {
    }

    public void mouseEntered(java.awt.event.MouseEvent evt) {
        if (evt.getSource() == BtnMoneda) {
            NewJFrame.this.BtnMonedaMouseEntered(evt);
        }
        else if (evt.getSource() == BtnDistancia) {
            NewJFrame.this.BtnDistanciaMouseEntered(evt);
        }
        else if (evt.getSource() == BtnMasa) {
            NewJFrame.this.BtnMasaMouseEntered(evt);
        }
        else if (evt.getSource() == BtnVolumen) {
            NewJFrame.this.BtnVolumenMouseEntered(evt);
        }
        else if (evt.getSource() == BtnTemperatura) {
            NewJFrame.this.BtnTemperaturaMouseEntered(evt);
        }
        else if (evt.getSource() == BtnConversor) {
            NewJFrame.this.BtnConversorMouseEntered(evt);
        }
    }

    public void mouseExited(java.awt.event.MouseEvent evt) {
        if (evt.getSource() == BtnMoneda) {
            NewJFrame.this.grupoMouseExited(evt);
        }
        else if (evt.getSource() == BtnDistancia) {
            NewJFrame.this.BtnDistanciaMouseExited(evt);
        }
        else if (evt.getSource() == BtnMasa) {
            NewJFrame.this.BtnMasaMouseExited(evt);
        }
        else if (evt.getSource() == BtnVolumen) {
            NewJFrame.this.BtnVolumenMouseExited(evt);
        }
        else if (evt.getSource() == BtnTemperatura) {
            NewJFrame.this.BtnTemperaturaMouseExited(evt);
        }
        else if (evt.getSource() == BtnConversor) {
            NewJFrame.this.BtnConversorMouseExited(evt);
        }
    }

    public void mousePressed(java.awt.event.MouseEvent evt) {
    }

    public void mouseReleased(java.awt.event.MouseEvent evt) {
    }// </editor-fold>//GEN-END:initComponents

    private void BtnConversorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConversorActionPerformed

        conversor.setMagnitudes(m);

        try {

            double a = Double.parseDouble(Txt1.getText());
            String b = Box1.getSelectedItem().toString();
            String c = Box2.getSelectedItem().toString();

            if ("Temperatura".equals(m)) {

                temp.setResultado(a, b, c);
                Txt2.setText(Double.toString(temp.getResultadoRedondeado(Integer.parseInt(jSpinner1.getValue().toString()))));

            } else {
                conversor.setResultado(a, b, c);

                Txt2.setText(Double.toString(conversor.getResultadoRedondeado(Integer.parseInt(jSpinner1.getValue().toString()))));
            }
        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(null, "Solo puede ingresar numeros");
            Txt1.setText("");
            Txt2.setText("");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnConversorActionPerformed

    private void Box2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box2ActionPerformed

    private void BtnTemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTemperaturaActionPerformed
        m = "Temperatura";
        ConversionActual.setText(m);
        Txt2.setText("");

        conversor.setMagnitudes(m);

        Box1.setModel(new DefaultComboBoxModel<>(conversor.getMagnitudes()));
        Box2.setModel(new DefaultComboBoxModel<>(conversor.getMagnitudes()));    }//GEN-LAST:event_BtnTemperaturaActionPerformed

    private void BtnMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMonedaActionPerformed
        m = "Moneda";
        ConversionActual.setText(m);
        Txt2.setText("");

        conversor.setMagnitudes(m);

        Box1.setModel(new DefaultComboBoxModel<>(conversor.getMagnitudes()));
        Box2.setModel(new DefaultComboBoxModel<>(conversor.getMagnitudes()));
// TODO add your handling code here:
    }//GEN-LAST:event_BtnMonedaActionPerformed

    private void BtnDistanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDistanciaActionPerformed
        m = "Distancia";
        ConversionActual.setText(m);
        Txt2.setText("");

        conversor.setMagnitudes(m);

        Box1.setModel(new DefaultComboBoxModel<>(conversor.getMagnitudes()));
        Box2.setModel(new DefaultComboBoxModel<>(conversor.getMagnitudes()));    }//GEN-LAST:event_BtnDistanciaActionPerformed

    private void BtnMasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMasaActionPerformed
        m = "Masa";
        ConversionActual.setText(m);
        Txt2.setText("");

        conversor.setMagnitudes(m);

        Box1.setModel(new DefaultComboBoxModel<>(conversor.getMagnitudes()));
        Box2.setModel(new DefaultComboBoxModel<>(conversor.getMagnitudes()));    }//GEN-LAST:event_BtnMasaActionPerformed

    private void BtnVolumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolumenActionPerformed
        m = "Volumen";
        ConversionActual.setText(m);
        Txt2.setText("");

        conversor.setMagnitudes(m);

        Box1.setModel(new DefaultComboBoxModel<>(conversor.getMagnitudes()));
        Box2.setModel(new DefaultComboBoxModel<>(conversor.getMagnitudes()));    }//GEN-LAST:event_BtnVolumenActionPerformed

    private void BtnConversorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnConversorKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            conversor.setMagnitudes(m);

            try {

                double a = Double.parseDouble(Txt1.getText());
                String b = Box1.getSelectedItem().toString();
                String c = Box2.getSelectedItem().toString();

                if ("Temperatura".equals(m)) {

                    temp.setResultado(a, b, c);
                    Txt2.setText(Double.toString(temp.getResultadoRedondeado(Integer.parseInt(jSpinner1.getValue().toString()))));

                } else {
                    conversor.setResultado(a, b, c);

                    Txt2.setText(Double.toString(conversor.getResultadoRedondeado(Integer.parseInt(jSpinner1.getValue().toString()))));
                }
            } catch (NumberFormatException e) {
            }
        }    }//GEN-LAST:event_BtnConversorKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Txt1.setText("");
        Txt2.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SwithActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SwithActionPerformed
        if(Swith.isSelected()){recursos.textoArcoiris(300, ConversionActual);}else{ConversionActual.setForeground(Color.WHITE);}
        recursos.cambiarTema(this);
        recursos.ImagenDeFondo(Swith,/*"giphyred.gif"*/ "blueSky.gif", JbackG, JbackG1, JbackG2);
        recursos.cambioConSwitch(Swith, BtnDistancia, BtnMoneda, BtnMasa, BtnTemperatura, BtnVolumen);
        recursos.cambioTemaIconos(Swith, aluraLogo, jPanel2, BtnDistancia, BtnMoneda, BtnMasa, BtnTemperatura, BtnVolumen);

        SwingUtilities.updateComponentTreeUI(this);      // TODO add your handling code here:
    }//GEN-LAST:event_SwithActionPerformed

    private void Txt1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            conversor.setMagnitudes(m);

            try {

                double a = Double.parseDouble(Txt1.getText());
                String b = Box1.getSelectedItem().toString();
                String c = Box2.getSelectedItem().toString();

                if ("Temperatura".equals(m)) {

                    temp.setResultado(a, b, c);
                    Txt2.setText(Double.toString(temp.getResultadoRedondeado(Integer.parseInt(jSpinner1.getValue().toString()))));

                } else {
                    conversor.setResultado(a, b, c);

                    Txt2.setText(Double.toString(conversor.getResultadoRedondeado(Integer.parseInt(jSpinner1.getValue().toString()))));
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Solo puede ingresar numeros");
                Txt1.setText("");
                Txt2.setText("");

            }
        }     }//GEN-LAST:event_Txt1KeyPressed

    private void BtnConversorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnConversorMouseEntered

        recursos.animacion(BtnConversor);

    }//GEN-LAST:event_BtnConversorMouseEntered

    private void BtnConversorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnConversorMouseExited

        BtnConversor.setBackground(new java.awt.Color(17, 58, 110));
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnConversorMouseExited

    private void grupoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grupoMouseExited
        recursos.animacionOff(BtnMoneda, Swith);
    }//GEN-LAST:event_grupoMouseExited

    private void BtnMonedaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMonedaMouseEntered
        recursos.animacion(BtnMoneda);        // TODO add your handling code here:
    }//GEN-LAST:event_BtnMonedaMouseEntered

    private void BtnDistanciaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnDistanciaMouseEntered
        recursos.animacion(BtnDistancia);    }//GEN-LAST:event_BtnDistanciaMouseEntered

    private void BtnMasaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMasaMouseEntered
        recursos.animacion(BtnMasa);    }//GEN-LAST:event_BtnMasaMouseEntered

    private void BtnVolumenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnVolumenMouseEntered
        recursos.animacion(BtnVolumen);    }//GEN-LAST:event_BtnVolumenMouseEntered

    private void BtnTemperaturaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnTemperaturaMouseEntered
        recursos.animacion(BtnTemperatura);   // TODO add your handling code here:
    }//GEN-LAST:event_BtnTemperaturaMouseEntered

    private void BtnDistanciaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnDistanciaMouseExited
        recursos.animacionOff(BtnDistancia, Swith);        // TODO add your handling code here:
    }//GEN-LAST:event_BtnDistanciaMouseExited

    private void BtnMasaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMasaMouseExited
        recursos.animacionOff(BtnMasa, Swith);        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnMasaMouseExited

    private void BtnVolumenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnVolumenMouseExited
        recursos.animacionOff(BtnVolumen, Swith);        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnVolumenMouseExited

    private void BtnTemperaturaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnTemperaturaMouseExited
        recursos.animacionOff(BtnTemperatura, Swith);        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnTemperaturaMouseExited

    /**
     * @param args the command line arguments
     */
    //@SuppressWarnings("unchecked")
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("flatLaf Light".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Box1;
    private javax.swing.JComboBox<String> Box2;
    private javax.swing.JButton BtnConversor;
    private javax.swing.JToggleButton BtnDistancia;
    private javax.swing.JToggleButton BtnMasa;
    private javax.swing.JToggleButton BtnMoneda;
    private javax.swing.JToggleButton BtnTemperatura;
    private javax.swing.JToggleButton BtnVolumen;
    private javax.swing.JLabel ConversionActual;
    private javax.swing.ButtonGroup GrupoDeBotones;
    private javax.swing.JLabel JbackG;
    private javax.swing.JLabel JbackG1;
    private javax.swing.JLabel JbackG2;
    private javax.swing.JToggleButton Swith;
    private javax.swing.JTextField Txt1;
    private javax.swing.JTextField Txt2;
    private javax.swing.JLabel aluraLogo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables
}
